# DEVELOPMENT
version: '3'
services:
  db:
    container_name: ma_diplom
    image: postgres:13.4-alpine
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
